### ISSUE TITLE
Bad serialisation of floats and integers

### ISSUE THREAD

**Issue by stedolan** [ygrek/ocaml-cbor#1]
In some cases, `CBOR.Simple` doesn't manage to decode values that it encoded:
```
# module CS = CBOR.Simple;;
module CS = CBOR.Simple
# `Int 3907650483 |> CS.encode |> CS.decode;;
- : CS.t = `Int (-387316813)
# `Float 1. |> CS.encode |> CS.decode;;
Exception: CBOR.Error "decode: extra data: len 10 pos 2".
```

**Comment by ygrek** [comment]
Thanks a lot for reporting!
Remains to do - roundtrip tests and switch ocplib-endian to integers which has all needed unsigned conversions.
