### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by joelburget** [ygrek/ocaml-cbor#12]
Hi ygrek, would you be willing to upload a new release? I'd really appreciate it. My CI for a package which depends on cbor is passing except for the failure fixed by https://github.com/ygrek/ocaml-cbor/commit/4a42a29f329c670cb24a9f08b41d39c64d9227f6.

**Comment by ygrek** [comment]
https://github.com/ocaml/opam-repository/pull/18075

**Comment by joelburget** [comment]
Thank you!
