### ISSUE TITLE
CTAP2 canonical CBOR

### ISSUE THREAD

**Issue by reynir** [ygrek/ocaml-cbor#18]
FIDO Alliance specifies a subset of CBOR called [CTAP2 canonical CBOR encoding form](https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#ctap2-canonical-cbor-encoding-form). Briefly, it restricts integer encoding to the most compact form, disallows indefinite length items and tags, and mandates an order on map keys.

For WebAuthn I modified ocaml-cbor to only accept CTAP2 canonical CBOR here: https://git.robur.io/robur/webauthn/src/branch/canonical/cbor/CBOR.ml

I understand if this is out of scope for this package.

**Comment by ygrek** [comment]
I would think it is totally in scope, submodule Simple kind of hints that some extensions were expected :) Also there is https://github.com/ygrek/ocaml-cbor/pull/8 which functorizes on the integer type. So I would gladly welcome a PR for CTAP2 submodule.
