### ISSUE TITLE
Support for compilation on 32bit and JS targets

### ISSUE THREAD

**Issue by adrien-n** [ygrek/ocaml-cbor#7]
I'm trying to use the library with js_of_ocaml and the following causes troubles:

    else if n < 4294967296 then (* optcomp int32 *)

Jsoo truncates 4294967296 to 0. I didn't even try to run the generated code. Instead I commented-out code to check that the corresponding warning disappeared.

I got rid of the warning with the following:

    else if Int64.(compare (of_int n) 4294967296) < 0 then

but haven't tried running the code yet.

**Comment by adrien-n** [comment]
I also noticed this line of code but I'm not sure of its purpose:

    let two_min_int32 = 2 * Int32.to_int Int32.min_int

**Comment by ygrek** [comment]
can you please provide a reproduce - e.g. how to build with js_of_ocaml / run tests, I am a total noob her (if it proves succesful would be nice to make it into a testcase later)

**Comment by adrien-n** [comment]
You can test with the following, assuming js_of_ocaml has been installed:

    echo 'let i = 4611686018427387903' > x.ml
    ocamlc -c x.ml
    js_of_ocaml x.cmo

It will output

    Warning: integer overflow: integer 0x3fffffffffffffff (4611686018427387903) truncated to 0xffffffff (-1); the generated code might be incorrect.

**Comment by joelburget** [comment]
I'm also affected by this -- here's a CI link turning up the same problem, if it's helpful: https://ci.ocamllabs.io/github/joelburget/lvca/commit/202fd12980db50a11002dcf3288267fc8ad8997f/variant/debian-10-4.11_arm32

```
#16 503.0 #     ocamlopt src/.cbor.objs/native/cBOR.{cmx,o} (exit 2)
#16 503.0 # (cd _build/default && /home/opam/.opam/4.11/bin/ocamlopt.opt -w -40 -g -I src/.cbor.objs/byte -I src/.cbor.objs/native -I /home/opam/.opam/4.11/lib/bytes -I /home/opam/.opam/4.11/lib/ocplib-endian -intf-suffix .ml -no-alias-deps -o src/.cbor.objs/native/cBOR.cmx -c -impl src/CBOR.ml)
#16 503.0 # File "src/CBOR.ml", line 36, characters 14-24:
#16 503.0 # 36 |   else if n < 4294967296 then (* optcomp int32 *)
#16 503.0 #                    ^^^^^^^^^^
#16 503.0 # Error: Integer literal exceeds the range of representable integers of type int
```

**Comment by ygrek** [comment]
I believe this is fixed with above PR, I was able to build test js program without warning.
